# Generated by Django 6.1 on 2026-08-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_restore_shipping_address_and_remove_legacy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(default='', help_text='Snapshot del nombre del producto al momento de la compra', max_length=200, verbose_name='nombre del producto'),
        ),
    ]
