# Generated by Django 6.1 on 2026-08-27 14:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderstatushistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código en mayúsculas. Ej: CARELY10', max_length=50, unique=True, verbose_name='código')),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje (%)'), ('fixed', 'Valor fijo (COP)')], default='percentage', max_length=10, verbose_name='tipo de descuento')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Porcentaje (ej: 10 = 10%) o valor fijo en COP (ej: 5000)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor del descuento')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='válido desde')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='válido hasta')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Dejar vacío para usos ilimitados.', null=True, verbose_name='límite de usos')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='usos realizados')),
                ('minimum_purchase', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal mínimo requerido para usar este cupón.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='mínimo de compra')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'cupón',
                'verbose_name_plural': 'cupones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='código de cupón'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='descuento aplicado'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.coupon', verbose_name='cupón'),
        ),
    ]
