# Generated by Django 6.1.1 on 2026-10-05 23:38

from django.db import migrations, models


NOTAS_POR_DEFECTO = 'Sin instrucciones adicionales'


def rellena_notas_vacias(apps, schema_editor):
    """
    Los pedidos anteriores guardaban cadena vacía cuando el cliente no dejaba
    notas. `AlterField` solo cambia el valor por defecto de filas nuevas, así
    que sin esto los pedidos ya creados quedarían con un hueco en pantalla.
    """
    Order = apps.get_model('orders', 'Order')
    Order.objects.filter(notes='').update(notes=NOTAS_POR_DEFECTO)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_add_coupon_model_and_order_discount_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, default='Sin instrucciones adicionales', verbose_name='notas'),
        ),
        migrations.RunPython(rellena_notas_vacias, migrations.RunPython.noop),
    ]
