# Generated by Django 6.0.6 on 2026-06-26 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('icon', models.CharField(help_text='Clase de Bootstrap Icons (ej: bi-emoji-wink)', max_length=50, verbose_name='icono')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='imagen')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='imagen')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('featured', models.BooleanField(default=False, verbose_name='destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.category', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['-created_at'],
            },
        ),
    ]
