# Generated by Django 6.1.1 on 2026-10-05 20:39

from django.db import migrations, models


def fill_reference(apps, schema_editor):
    """
    Le da una referencia a los pagos que ya existían antes de Wompi.

    La columna llega nula porque en la base previa no había nada que llenar; sin
    este paso, esos pagos quedarían sin referencia y no se podrían cobrar.
    """
    Payment = apps.get_model('payments', 'Payment')
    for payment in Payment.objects.filter(reference__isnull=True).iterator():
        payment.reference = f'CARELY-MIGRATED-{payment.pk}'
        payment.save(update_fields=['reference'])


def unfill_reference(apps, schema_editor):
    """Deshace el relleno para que la reversa pueda dejar la columna nula."""
    apps.get_model('payments', 'Payment').filter(
        reference__startswith='CARELY-MIGRATED-',
    ).update(reference=None)


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_amount_alter_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('wompi', 'Wompi'), ('simulado', 'Simulado')], default='wompi', max_length=20, verbose_name='pasarela'),
        ),
        migrations.AddField(
            model_name='payment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Datos no sensibles de la respuesta de la pasarela (tipo de método, IP, centavos cobrados).', verbose_name='metadatos'),
        ),
        migrations.AddField(
            model_name='payment',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Momento en que la transacción alcanzó un estado final.', null=True, verbose_name='procesado en'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, editable=False, help_text='Referencia única de la transacción en la pasarela. Solo admite letras, dígitos, guiones y guiones bajos.', max_length=255, null=True, unique=True, verbose_name='referencia'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status_message',
            field=models.CharField(blank=True, help_text='Texto que devuelve la pasarela con el último estado recibido.', max_length=255, verbose_name='mensaje del estado'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Tarjeta de crédito'), ('pse', 'PSE'), ('nequi', 'Nequi'), ('bancolombia_transfer', 'Transferencia Bancolombia'), ('daviplata', 'Daviplata'), ('efectivo', 'Efectivo')], default='card', max_length=30, verbose_name='método de pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('anulado', 'Anulado'), ('cancelado', 'Cancelado'), ('error', 'Error')], default='pendiente', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Identificador que asigna la pasarela. Llenado cuando Wompi responde o notifica el evento.', max_length=255, null=True, unique=True, verbose_name='ID de transacción'),
        ),
        migrations.RunPython(fill_reference, unfill_reference),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, editable=False, help_text='Referencia única de la transacción en la pasarela. Solo admite letras, dígitos, guiones y guiones bajos.', max_length=255, unique=True, verbose_name='referencia'),
        ),
    ]
