# Generated by Django 6.1 on 2026-08-27 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=150, verbose_name='nombre del destinatario')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono de contacto')),
                ('address_line', models.CharField(max_length=255, verbose_name='dirección principal')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='complemento de dirección')),
                ('city', models.CharField(max_length=100, verbose_name='ciudad o municipio')),
                ('department', models.CharField(max_length=100, verbose_name='departamento')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='código postal')),
                ('instructions', models.TextField(blank=True, verbose_name='indicaciones adicionales')),
                ('is_default', models.BooleanField(default=False, verbose_name='dirección predeterminada')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'dirección',
                'verbose_name_plural': 'direcciones',
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='idx_address_user_active')],
            },
        ),
    ]
