# Generated by Django 6.1.1 on 2026-10-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_department_city_address_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_terms_at',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el usuario aceptó los términos y condiciones vigentes.', null=True, verbose_name='términos aceptados en'),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_version',
            field=models.CharField(blank=True, help_text='Identificador de la versión de los términos aceptados, p. ej. 2026-01-01.', max_length=20, verbose_name='versión de los términos aceptados'),
        ),
    ]
