# Generated by Django 6.1.1 on 2026-10-02 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_accepted_terms_at_user_terms_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='Fecha en que la cuenta fue deshabilitada. Se vacía al reactivarla.', null=True, verbose_name='deshabilitada en'),
        ),
        migrations.AddField(
            model_name='user',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='Administrador que deshabilitó la cuenta. Vacío si la deshabilitó el titular.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_accounts', to=settings.AUTH_USER_MODEL, verbose_name='deshabilitada por'),
        ),
    ]
