# Generated by Django 6.1.1 on 2026-10-02 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_deactivated_at_user_deactivated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='El titular confirmó que tiene acceso al correo registrado.', verbose_name='verificación en dos pasos activada'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='verificación en dos pasos activada en'),
        ),
        migrations.CreateModel(
            name='TwoFactorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('enable', 'Activar la verificación en dos pasos'), ('deactivate', 'Deshabilitar la cuenta'), ('reactivate', 'Reactivar la cuenta')], max_length=20, verbose_name='uso')),
                ('code_hash', models.CharField(help_text='Código cifrado con el hasher de contraseñas de Django.', max_length=128, verbose_name='hash del código')),
                ('expires_at', models.DateTimeField(verbose_name='expira en')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='usado en')),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='intentos fallidos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_codes', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'código de verificación en dos pasos',
                'verbose_name_plural': 'códigos de verificación en dos pasos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose'], name='idx_twofactor_user_purpose')],
            },
        ),
    ]
