# Generated by Django 6.1.1 on 2026-10-06 03:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), help_text='Descuento en porcentaje (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='descuento (%)'),
        ),
    ]
